[package]
name = "lempify"
version = "0.1.0"
description = "LEMP Stack Local Development App."
authors = ["jaredrethman"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "macos-private-api", "tray-icon" ] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
users = "0.11.0"
dirs = "6.0.0"
tauri-plugin-shell = "2.2.1"
whoami = "1.6.0"
