server {
    listen 80;
    server_name {{DOMAIN}};

	## Lempify SSL ##

    root /opt/homebrew/var/www/{{DOMAIN}};
    index index.php index.html;
    client_max_body_size 64M;

    access_log /opt/homebrew/var/www/{{DOMAIN}}/logs/access.log;
    error_log /opt/homebrew/var/www/{{DOMAIN}}/logs/error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass {{PHP_SOCKET}};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 120;
    }
}