[package]
name = "lempifyd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lempifyd"
path = "lempifyd.rs"

[dependencies]
shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "7.0.3"
users = "0.11.0"
dirs = "6.0.0"
whoami = "1.6.0"